name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install

      - name: Lint
        run: yarn lint

      - name: Type checking
        run: yarn type-check

      - name: Run unit tests
        run: yarn test

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium

      - name: Run Playwright E2E Tests
        run: yarn test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
